OJ-1305: Use redaction deserializer in Address-cri
alphagov/di-ipv-cri-address-api pull request #534
Opened 2023-03-24 13:42 UTC by jkunle

## Proposed changes

Use the Redaction deserialiser in common-lib

### What changed

[A redaction deserializer was added to common-lib we can use this to strip possible PII](https://github.com/alphagov/di-ipv-cri-lib/pull/201)

### Why did it change

### Issue tracking

- [OJ-1305](https://govukverify.atlassian.net/browse/OJ-1305)

2023-03-27 15:25 UTC, merlinc submitted a review, later dismissed

2023-04-28 09:02 UTC, surajkumar requested changes

2023-04-28 09:02 UTC, surajkumar commented on lib/src/main/java/uk/gov/di/ipv/cri/address/library/service/AddressService.java
> +            throw new AddressProcessingException("could not parse addresses..." + e.getMessage());
Maybe make this error more meaningful e.g. `"Jackson could not parse addresses to a List of CanonicalAddress": + e.getMessage();`?

2023-04-28 15:02 UTC, surajkumar approved these changes
OK as discussed

2023-05-02 08:21 UTC, merged